### ISSUE TITLE
This salad recipe is nasty !

### ISSUE THREAD

**Issue by dianaxnav** [Channelislanders/saladrecipe#1]
I didn't like it.

**Comment by p-park6** [comment]
Did you try adding some croutons? They add an extra crunch.

**Comment by dianaxnav** [comment]
@p-park6 yessssss, any other recs?

**Comment by olleholt** [comment]
strawberries and pistachios

**Comment by p-park6** [comment]
@olleholt yoooo that sounds good actually

**Comment by dianaxnav** [comment]
I feel ganged up on

**Comment by p-park6** [comment]
@dianaxnav @olleholt 

what dressing do you like on your salad?

- [ ]  Ceaser
- [ ] ranch
- [ ] balsamic vinegar
- [ ] thousland island
- [ ] no dressing

**Comment by olleholt** [comment]
balsamic is good with strawberries, not ranch
